Adapt daemon for the sensors installed on the Xiaomi R3D
Remove depends from bash (using ash from preinstalled busybox)

diff --git a/package/alpine-fan-control/files/alpine-fan-controller b/package/alpine-fan-control/files/alpine-fan-controller
--- a/package/alpine-fan-control/files/alpine-fan-controller
+++ b/package/alpine-fan-control/files/alpine-fan-controller
@@ -1,105 +1,135 @@
-#!/bin/bash
+#!/bin/sh
 
-HYSTERESIS=0
+# set temps (in degrees C) and corresponding fan speeds 
+# in ascending order and with the same amount of values
+TEMP_MIN=$1
+SPEED_MIN=$2
+TEMP_MID=$3
+SPEED_MID=$4
+TEMP_MAX=$5
+SPEED_MAX=$6
 SLEEP_INTERVAL=$7
 DEBUG=$8
+
+DRV_SPEED_MIN=0
+DRV_SPEED_MAX=255
+
+LOGPREFIX="alpine-fan-controller"
+HYSTERESIS=0
 TEMP_AT_LAST_SPEED_CHANGE=0
 
-# set temps (in degrees C) and corresponding fan speeds in ascending order and with the same amount of values
-TEMPS=( $1 $3 $5 )
-SPEED=( $2 $4 $6 )
-
-# hwmon paths, hardcoded for alpine platform, adjust as needed
-FILE_SPEED=$(echo /sys/bus/i2c/devices/0-003e/hwmon/hwmon0/fan1_target)
-FILE_TEMP=$(echo /sys/class/thermal/thermal_zone0/temp)
-
-[[ -f "$FILE_SPEED" && -f "$FILE_TEMP" ]] || { logger "alpine-fan-controller: invalid hwmon files" ; exit 1; }
-
-# check if amount of temps and speed values match
-if [ "${#TEMPS[@]}" -ne "${#SPEED[@]}" ]
-then
-  echo "Amount of temperature and speed values does not match"
-  exit 1
-fi
-
 # checking for privileges
-if [ $UID -ne 0 ]
-then
-  echo "Writing to sysfs requires privileges, relaunch as root"
-  exit 1
+if [ $UID -ne 0 ]; then
+	echo "Writing to sysfs requires privileges, relaunch as root"
+	exit 1
 fi
 
-function debug {
-  if [ $DEBUG -gt 0 ]
-  then
-    logger $1
-  fi
+# hwmon paths, hardcoded for Xiaomi R3D, adjust as needed
+FILE_SPEED=$( grep -l emc2301 /sys/class/hwmon/hwmon*/name )
+[ -f "$FILE_SPEED" ] || { logger "$LOGPREFIX: fan controller EMC2301 not found" ; exit 1; }
+FILE_SPEED=$( dirname "$FILE_SPEED" 2>/dev/null )
+FILE_SPEED=$FILE_SPEED/pwm1
+[ -f "$FILE_SPEED" ] || { logger "$LOGPREFIX: Fan controller EMC2301 not found" ; exit 1; }
+
+FILE_TEMP=$( grep -l tmp75 /sys/class/hwmon/hwmon*/name )
+[ -f "$FILE_TEMP" ] || { logger "$LOGPREFIX: thermal sensor TMP75 not found" ; exit 1; }
+FILE_TEMP=$( dirname "$FILE_TEMP" 2>/dev/null )
+FILE_TEMP=$FILE_TEMP/temp1_input
+[ -f "$FILE_TEMP" ] || { logger "$LOGPREFIX: Thermal sensor TMP75 not found" ; exit 1; }
+
+function log_debug {
+	if [ $DEBUG -gt 0 ]; then
+		logger "$LOGPREFIX: $1"
+	fi
+}
+
+function get_speed {
+	local speed=$(cat $FILE_SPEED)
+	speed=$(( $SPEED_MAX * $speed / $DRV_SPEED_MAX ))
+	echo $speed
+}
+
+function internal_set_speed {
+	local speed=$1
+	local value=$(( $DRV_SPEED_MAX * $speed / $SPEED_MAX ))
+	[ $value -lt $DRV_SPEED_MIN ] && value=$DRV_SPEED_MIN
+	[ $value -gt $DRV_SPEED_MAX ] && value=$DRV_SPEED_MAX
+	echo $value > $FILE_SPEED
 }
 
 function set_speed {
-  NEW_SPEED=$1
-  OLD_SPEED=$(cat $FILE_SPEED)
+	local NEW_SPEED=$1
+	local CUR_SPEED=$( get_speed )
+	local TEMP=$(cat $FILE_TEMP)
 
-  debug "current speed: $OLD_SPEED, requested to set speed to $NEW_SPEED"
+	log_debug "current speed: $CUR_SPEED, requested to set speed to $NEW_SPEED"
+	
+	local tmp=$TEMP_AT_LAST_SPEED_CHANGE
+	if [ -z "$tmp" ] || [ "$TEMP" -gt "$tmp" ] || [ $(( $TEMP + HYSTERESIS )) -le "$tmp" ]; then
+		log_debug "current temp: $TEMP"
+		echo "temp at last change was $TEMP_AT_LAST_SPEED_CHANGE"
+		echo "changing speed to $NEW_SPEED"
+		internal_set_speed $NEW_SPEED
+		TEMP_AT_LAST_SPEED_CHANGE=$TEMP
+	else
+		log_debug "not changing speed, we just did at $TEMP_AT_LAST_SPEED_CHANGE, next change when below $((TEMP_AT_LAST_SPEED_CHANGE - HYSTERESIS))"
+	fi
+}
 
-  if [ -z "$TEMP_AT_LAST_SPEED_CHANGE" ] || [ "$TEMP" -gt "$TEMP_AT_LAST_SPEED_CHANGE" ] || [ $(($(cat $FILE_TEMP) + HYSTERESIS)) -le "$TEMP_AT_LAST_SPEED_CHANGE" ]; then
-    $DEBUG || echo "current temp: $TEMP"
-    echo "temp at last change was $TEMP_AT_LAST_SPEED_CHANGE"
-    echo "changing speed to $NEW_SPEED"
-    echo "$NEW_SPEED" > "$FILE_SPEED"
-    TEMP_AT_LAST_SPEED_CHANGE=$(cat $FILE_TEMP)
-  else
-    debug "not changing speed, we just did at $TEMP_AT_LAST_SPEED_CHANGE, next change when below $((TEMP_AT_LAST_SPEED_CHANGE - HYSTERESIS))"
-  fi
+function set_speed_adv {
+	# interpolate linearly
+	local LOWERTEMP=$1
+	local LOWERSPEED=$2
+	local HIGHERTEMP=$3
+	local HIGHERSPEED=$4
+	local TEMP=$5
+	[ -z "$TEMP" ] && TEMP=$(cat $FILE_TEMP)
+	local value=$(( ( $TEMP - $LOWERTEMP ) * ( $HIGHERSPEED - $LOWERSPEED ) ))
+	local SPEED=$(( $value / ( $HIGHERTEMP - $LOWERTEMP ) + $LOWERSPEED ))
+	log_debug "interpolated speed value for temperature $TEMP is: $SPEED"
+	set_speed "$SPEED"
 }
 
 function interpolate_speed {
-  i=0
-  TEMP=$(cat $FILE_TEMP)
+	local i=0
+	local TEMP=$(cat $FILE_TEMP)
 
-  debug "current temp: $TEMP"
+	log_debug "current temp: $TEMP"
 
-  if [[ $TEMP -le ${TEMPS[0]} ]]; then
-    # below first point in list, set to min speed
-    set_speed "${SPEED[i]}"
-    return
-  elif [[ $TEMP -gt ${TEMPS[-1]} ]]; then
-    # above last point in list, set to max speed
-    set_speed "${SPEED[-1]}"
-    return
-  fi
-
-  for i in "${!TEMPS[@]}"; do
-    if [[ $TEMP -gt ${TEMPS[$i]} ]]; then
-      continue
-    fi
-
-    # interpolate linearly
-    LOWERTEMP=${TEMPS[i-1]}
-    HIGHERTEMP=${TEMPS[i]}
-    LOWERSPEED=${SPEED[i-1]}
-    HIGHERSPEED=${SPEED[i]}
-    SPEED=$(( ( ($TEMP - $LOWERTEMP) * ( $HIGHERSPEED - $LOWERSPEED ) / ( $HIGHERTEMP - $LOWERTEMP ) ) + $LOWERSPEED ))
-    debug "interpolated speed value for temperature $TEMP is: $SPEED"
-    set_speed "$SPEED"
-    return
-  done
+	if [ $TEMP -le $TEMP_MIN ]; then
+		# below first point in list, set to min speed
+		set_speed $SPEED_MIN
+		return
+	fi
+	if [ $TEMP -gt $TEMP_MAX ]; then
+		# above last point in list, set to max speed
+		set_speed $SPEED_MAX
+		return
+	fi
+	if [ $TEMP -le $TEMP_MAX ]; then
+		set_speed_adv $TEMP_MID $SPEED_MID $TEMP_MAX $SPEED_MAX $TEMP
+		return
+	fi
+	if [ $TEMP -le $TEMP_MID ]; then
+		set_speed_adv $TEMP_MIN $SPEED_MIN $TEMP_MID $SPEED_MID $TEMP
+		return
+	fi
 }
 
 function reset_on_exit {
-  echo "exiting, going to max fan speed for safety..."
-  echo 4000 > /sys/bus/i2c/devices/0-003e/fan1_target
-  exit 0
+	echo "exiting, going to max fan speed for safety..."
+	internal_set_speed 999999
+	exit 0
 }
 
 # always try to reset fans on exit
 trap "reset_on_exit" SIGINT SIGTERM
 
 function run_daemon {
-  while :; do
-    interpolate_speed
-    sleep $SLEEP_INTERVAL
-  done
+	while true; do
+		interpolate_speed
+		sleep $SLEEP_INTERVAL
+	done
 }
 
 # finally start the loop
